export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_BY_GENRE = 'GET_MOVIES_BY_GENRE';
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const CLEAR_SELECTED_MOVIE = 'CLEAR_SELECTED_MOVIE';
export const ADD_MOVIE = 'ADD_MOVIE';
export const EDIT_MOVIE = 'EDIT_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
